//! The sounds an expansion adds, so a scene that reaches for one can be read.
//!
//! An expansion lives in the instrument the way the factory banks do — a scene only ever *points*
//! at it — but Roland's main sound list stops at the base instrument, so `EXZ EXZ008 PC 012` is as
//! far as [`crate::factory`] gets. These catalogs are the rest: every sound of every expansion this
//! build knows, captured page by page from a FANTOM-6 and generated by
//! `tools/gen_expansion_catalog.py` into `expansion_sounds.tsv`.
//!
//! Catalogs are keyed by **product code** — `EXZ007`, `EXSN02`, `SH101` — because the contents of
//! an expansion are the same for everyone who owns it. The address each product was observed
//! answering at is recorded per sound, and [`lookup`] reads names back by it; whether that address
//! is the same on every instrument is not something one instrument can say.
//!
//! Ownership is not consulted. A scene naming a tone the reader does not own is exactly the case
//! an install guide exists for, so the name is given either way.

use std::collections::HashMap;
use std::sync::OnceLock;

use crate::factory::FactorySound;
use crate::model::{ToneAddress, ToneType};

/// One sound of one expansion.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ExpansionSound {
    /// The product that carries it — the catalog's key.
    pub product: &'static str,
    /// The sound itself, in the shape every other built-in list uses.
    pub sound: FactorySound<'static>,
}

/// One expansion, as a catalog rather than a list of sounds.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Product {
    pub code: &'static str,
    /// The engine that plays it, derived from the addresses its sounds sit at.
    pub engine: ToneType,
    /// Every `(MSB, LSB)` bank page this product was observed answering at, in address order.
    pub banks: Vec<(u8, u8)>,
    pub sounds: usize,
}

const TABLE_TSV: &str = include_str!("expansion_sounds.tsv");

/// Every expansion sound this build carries, by product then address.
pub fn all() -> impl Iterator<Item = ExpansionSound> {
    index().rows.iter().copied()
}

/// The expansions this build can name, in product-code order.
pub fn products() -> &'static [Product] {
    &index().products
}

/// Every sound of one expansion, or nothing if no catalog carries that code.
pub fn catalog(product: &str) -> impl Iterator<Item = ExpansionSound> + '_ {
    all().filter(move |entry| entry.product == product)
}

/// The expansion sound at an address, when a bundled catalog names one there.
pub fn lookup(address: ToneAddress) -> Option<ExpansionSound> {
    index().by_address.get(&key(address)).copied()
}

struct Index {
    rows: Vec<ExpansionSound>,
    by_address: HashMap<(u8, u8, u8), ExpansionSound>,
    products: Vec<Product>,
}

fn index() -> &'static Index {
    static INDEX: OnceLock<Index> = OnceLock::new();
    INDEX.get_or_init(|| {
        let rows: Vec<ExpansionSound> = parse(TABLE_TSV).collect();
        let by_address = rows
            .iter()
            .map(|row| (key(row.sound.address), *row))
            .collect();
        let mut products: Vec<Product> = Vec::new();
        for row in &rows {
            let bank = (row.sound.address.msb, row.sound.address.lsb);
            match products.iter_mut().find(|seen| seen.code == row.product) {
                Some(product) => {
                    if product.banks.last() != Some(&bank) {
                        product.banks.push(bank);
                    }
                    product.sounds += 1;
                }
                None => products.push(Product {
                    code: row.product,
                    engine: row.sound.engine(),
                    banks: vec![bank],
                    sounds: 1,
                }),
            }
        }
        Index {
            rows,
            by_address,
            products,
        }
    })
}

fn key(address: ToneAddress) -> (u8, u8, u8) {
    (address.msb, address.lsb, address.pc)
}

/// Read a catalog in the shape `tools/gen_expansion_catalog.py` writes: a product code, then the
/// six columns of a sound list, tab separated, one header line.
fn parse(text: &'static str) -> impl Iterator<Item = ExpansionSound> {
    text.lines().skip(1).filter_map(|line| {
        let mut field = line.split('\t');
        let product = field.next()?;
        let msb = field.next()?.parse().ok()?;
        let lsb = field.next()?.parse().ok()?;
        // The list prints `PC` counting from one; a zone stores it counting from zero.
        let pc = field.next()?.parse::<u8>().ok()?.checked_sub(1)?;
        let number = field.next()?.parse().unwrap_or(0);
        let name = field.next()?.trim();
        // A blank slot is not a sound.
        (!name.is_empty()).then(|| ExpansionSound {
            product,
            sound: FactorySound {
                address: ToneAddress { msb, lsb, pc },
                number,
                name,
                category: field.next().unwrap_or("").trim(),
            },
        })
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::ToneRef;

    /// The generator's product table and [`ToneRef::bank`] are two statements of one fact. This is
    /// what keeps them from drifting apart.
    #[test]
    fn every_row_is_keyed_as_the_address_taxonomy_keys_it() {
        for entry in all() {
            let address = entry.sound.address;
            let reference = ToneRef::new(address.msb, address.lsb, address.pc, None);
            assert_eq!(
                reference.bank(),
                Some(entry.product),
                "{}/{}",
                address.msb,
                address.lsb
            );
            assert_ne!(entry.sound.engine(), ToneType::Unknown);
        }
    }

    #[test]
    fn a_scene_reference_reads_back_as_a_name() {
        // EXZ008 answers at MSB 93 / LSB 11..14; the sound list prints PC counting from one.
        let sound = lookup(ToneAddress {
            msb: 93,
            lsb: 11,
            pc: 0,
        })
        .expect("EXZ008 PC 000");
        assert_eq!(sound.product, "EXZ008");
        assert_eq!(sound.sound.name, "Stereo Piano");

        // EXSN02 30 is `Phaser TineEP RD` in Roland's own list for the same expansion.
        let exsn = lookup(ToneAddress {
            msb: 105,
            lsb: 65,
            pc: 29,
        })
        .expect("EXSN02 PC 029");
        assert_eq!(exsn.sound.name, "Phaser TineEP RD");
        assert_eq!(exsn.sound.category, "");
    }

    /// A product nobody has dumped yet reads exactly as it did before the catalogs existed.
    #[test]
    fn an_address_no_catalog_covers_stays_unnamed() {
        let address = ToneAddress {
            msb: 107,
            lsb: 66,
            pc: 0,
        };
        assert_eq!(lookup(address), None);

        // The ACB SH-101 is a named bank with no catalog: ACB is the one engine that cannot be
        // read back from the instrument, so its names wait on a document. Bank and program, and
        // no invented name.
        let reference = ToneRef::new(address.msb, address.lsb, address.pc, None);
        assert_eq!(reference.bank(), Some("SH101"));
        assert_eq!(reference.name(), None);
    }

    #[test]
    fn a_product_records_the_pages_it_was_observed_at() {
        let exz007 = products()
            .iter()
            .find(|product| product.code == "EXZ007")
            .expect("EXZ007");
        assert_eq!(exz007.engine, ToneType::Exz);
        assert_eq!(exz007.banks, [(93, 7), (93, 8), (93, 9), (93, 10)]);
        assert_eq!(exz007.sounds, catalog("EXZ007").count());
    }
}
