//! The sounds an expansion adds, so a scene that reaches for one can be read.
//!
//! An expansion lives in the instrument the way the factory banks do — a scene only ever *points*
//! at it — but Roland's main sound list stops at the base instrument, so `EXZ EXZ008 PC 012` is as
//! far as [`crate::factory`] gets. These catalogs are the rest: every sound of every expansion this
//! build knows, captured page by page from a FANTOM-6 and generated by
//! `tools/gen_expansion_catalog.py` into `expansion_sounds.tsv`.
//!
//! Catalogs are keyed by **product code** — `EXZ007`, `EXSN02`, `SH101` — because the contents of
//! an expansion are the same for everyone who owns it. The address each product was observed
//! answering at is recorded per sound, and [`lookup`] reads names back by it; whether that address
//! is the same on every instrument is not something one instrument can say.
//!
//! Ownership is not consulted. A scene naming a tone the reader does not own is exactly the case
//! an install guide exists for, so the name is given either way.

use std::collections::HashMap;
use std::sync::OnceLock;

use crate::factory::FactorySound;
use crate::model::{ToneAddress, ToneType};

/// One sound of one expansion.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ExpansionSound {
    /// The product that carries it — the catalog's key.
    pub product: &'static str,
    /// The sound itself, in the shape every other built-in list uses.
    pub sound: FactorySound<'static>,
}

/// The kind of expansion a product is — how Roland sells them and how the panel lists them.
///
/// Derived from the product code rather than from the engine its sounds answer on: `EXZ003` is a
/// wave expansion whose sounds happen to be drum kits, and grouping it under "Drum" would put it
/// somewhere its owner would never look for it.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
#[cfg_attr(feature = "serde", derive(serde::Serialize, serde::Deserialize))]
#[cfg_attr(feature = "serde", serde(rename_all = "kebab-case"))]
pub enum Family {
    /// `EXZ*` — waves the ZEN-Core engine plays, and the drum kits built on them.
    Wave,
    /// `EXSN*` — SuperNATURAL acoustic and electric piano expansions.
    SuperNatural,
    /// The modelled instruments: `JP8`, `JU106`, `SH101`, `n/zyme` and the rest.
    Model,
    /// `M09X01` and its kin, played by the V-Piano engine.
    VPiano,
    /// A product this version cannot place. Listed rather than hidden.
    Other,
}

impl Family {
    /// Which family a product code belongs to, given the engine its sounds answer on.
    pub fn of(code: &str, engine: ToneType) -> Self {
        match () {
            _ if code.starts_with("EXZ") => Self::Wave,
            _ if code.starts_with("EXSN") => Self::SuperNatural,
            _ if engine == ToneType::Model => Self::Model,
            _ if engine == ToneType::VPiano => Self::VPiano,
            _ => Self::Other,
        }
    }
}

/// One expansion, as a catalog rather than a list of sounds.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Product {
    pub code: &'static str,
    /// What kind of expansion it is, for a list that groups them.
    pub family: Family,
    /// The engine that plays it, derived from the addresses its sounds sit at.
    pub engine: ToneType,
    /// Every `(MSB, LSB)` bank page this product was observed answering at, in address order.
    pub banks: Vec<(u8, u8)>,
    pub sounds: usize,
}

const TABLE_TSV: &str = include_str!("expansion_sounds.tsv");

/// Every expansion sound this build carries, by product then address.
pub fn all() -> impl Iterator<Item = ExpansionSound> {
    index().rows.iter().copied()
}

/// The expansions this build can name, in product-code order.
pub fn products() -> &'static [Product] {
    &index().products
}

/// Every sound of one expansion, or nothing if no catalog carries that code.
pub fn catalog(product: &str) -> impl Iterator<Item = ExpansionSound> + '_ {
    all().filter(move |entry| entry.product == product)
}

/// The expansion sound at an address, when a bundled catalog names one there.
pub fn lookup(address: ToneAddress) -> Option<ExpansionSound> {
    index().by_address.get(&key(address)).copied()
}

/// The product a partial's **wave group id** names — `1005` is `EXZ005`.
///
/// The id is `1000 + n` for `EXZnnn`, and it identifies the product rather than the bank page the
/// expansion was installed at. Only a group-type-1 partial carries one at all (see
/// [`crate::container::expansion_banks`]).
///
/// The arithmetic is applied only to products this build carries a catalog for. An id past those
/// is left undecoded rather than turned into a code for an expansion nobody has seen: the rule
/// would happily answer `EXZ200` for id 1200, and a confidently wrong name is the failure this
/// whole decode exists to avoid. Capturing that product's catalog is what makes its id readable.
pub fn wave_group_product(id: u16) -> Option<&'static str> {
    let number = id.checked_sub(EXZ_WAVE_GROUP_BASE)?;
    let code = format!("EXZ{number:03}");
    products()
        .iter()
        .find(|product| product.code == code)
        .map(|product| product.code)
}

/// What a wave expansion's group id counts up from; see [`wave_group_product`].
const EXZ_WAVE_GROUP_BASE: u16 = 1000;

struct Index {
    rows: Vec<ExpansionSound>,
    by_address: HashMap<(u8, u8, u8), ExpansionSound>,
    products: Vec<Product>,
}

fn index() -> &'static Index {
    static INDEX: OnceLock<Index> = OnceLock::new();
    INDEX.get_or_init(|| {
        let rows: Vec<ExpansionSound> = parse(TABLE_TSV).collect();
        let by_address = rows
            .iter()
            .map(|row| (key(row.sound.address), *row))
            .collect();
        let mut products: Vec<Product> = Vec::new();
        for row in &rows {
            let bank = (row.sound.address.msb, row.sound.address.lsb);
            match products.iter_mut().find(|seen| seen.code == row.product) {
                Some(product) => {
                    if product.banks.last() != Some(&bank) {
                        product.banks.push(bank);
                    }
                    product.sounds += 1;
                }
                None => products.push(Product {
                    code: row.product,
                    family: Family::of(row.product, row.sound.engine()),
                    engine: row.sound.engine(),
                    banks: vec![bank],
                    sounds: 1,
                }),
            }
        }
        Index {
            rows,
            by_address,
            products,
        }
    })
}

fn key(address: ToneAddress) -> (u8, u8, u8) {
    (address.msb, address.lsb, address.pc)
}

/// Read a catalog in the shape `tools/gen_expansion_catalog.py` writes: a product code, then the
/// six columns of a sound list, tab separated, one header line.
fn parse(text: &'static str) -> impl Iterator<Item = ExpansionSound> {
    text.lines().skip(1).filter_map(|line| {
        let mut field = line.split('\t');
        let product = field.next()?;
        let msb = field.next()?.parse().ok()?;
        let lsb = field.next()?.parse().ok()?;
        // The list prints `PC` counting from one; a zone stores it counting from zero.
        let pc = field.next()?.parse::<u8>().ok()?.checked_sub(1)?;
        let number = field.next()?.parse().unwrap_or(0);
        let name = field.next()?.trim();
        // A blank slot is not a sound.
        (!name.is_empty()).then(|| ExpansionSound {
            product,
            sound: FactorySound {
                address: ToneAddress { msb, lsb, pc },
                number,
                name,
                category: field.next().unwrap_or("").trim(),
            },
        })
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::ToneRef;

    /// The generator's product table and [`ToneRef::bank`] are two statements of one fact. This is
    /// what keeps them from drifting apart.
    #[test]
    fn every_row_is_keyed_as_the_address_taxonomy_keys_it() {
        for entry in all() {
            let address = entry.sound.address;
            let reference = ToneRef::new(address.msb, address.lsb, address.pc, None);
            assert_eq!(
                reference.bank(),
                Some(entry.product),
                "{}/{}",
                address.msb,
                address.lsb
            );
            assert_ne!(entry.sound.engine(), ToneType::Unknown);
        }
    }

    #[test]
    fn a_scene_reference_reads_back_as_a_name() {
        // EXZ008 answers at MSB 93 / LSB 11..14; the sound list prints PC counting from one.
        let sound = lookup(ToneAddress {
            msb: 93,
            lsb: 11,
            pc: 0,
        })
        .expect("EXZ008 PC 000");
        assert_eq!(sound.product, "EXZ008");
        assert_eq!(sound.sound.name, "Stereo Piano");

        // EXSN02 30 is `Phaser TineEP RD` in Roland's own list for the same expansion.
        let exsn = lookup(ToneAddress {
            msb: 105,
            lsb: 65,
            pc: 29,
        })
        .expect("EXSN02 PC 029");
        assert_eq!(exsn.sound.name, "Phaser TineEP RD");
        assert_eq!(exsn.sound.category, "");
    }

    /// A product nobody has dumped yet reads exactly as it did before the catalogs existed.
    #[test]
    fn an_address_no_catalog_covers_stays_unnamed() {
        let address = ToneAddress {
            msb: 107,
            lsb: 66,
            pc: 0,
        };
        assert_eq!(lookup(address), None);

        // The ACB SH-101 is a named bank with no catalog: ACB is the one engine that cannot be
        // read back from the instrument, so its names wait on a document. Bank and program, and
        // no invented name.
        let reference = ToneRef::new(address.msb, address.lsb, address.pc, None);
        assert_eq!(reference.bank(), Some("SH101"));
        assert_eq!(reference.name(), None);
    }

    #[test]
    fn a_product_records_the_pages_it_was_observed_at() {
        let exz007 = products()
            .iter()
            .find(|product| product.code == "EXZ007")
            .expect("EXZ007");
        assert_eq!(exz007.engine, ToneType::Exz);
        assert_eq!(exz007.banks, [(93, 7), (93, 8), (93, 9), (93, 10)]);
        assert_eq!(exz007.sounds, catalog("EXZ007").count());
    }

    /// An expansion belongs to the family its code says it does, not to the engine one of its
    /// banks happens to sit at: `EXZ003` is a wave expansion whose sounds are drum kits.
    #[test]
    fn a_product_is_grouped_by_what_it_is_rather_than_where_it_answers() {
        let family = |code: &str| {
            products()
                .iter()
                .find(|product| product.code == code)
                .map(|product| product.family)
        };
        assert_eq!(family("EXZ003"), Some(Family::Wave));
        assert_eq!(family("EXZ012"), Some(Family::Wave));
        assert_eq!(family("EXSN02"), Some(Family::SuperNatural));
        assert_eq!(family("JU106"), Some(Family::Model));
        assert_eq!(family("n/zyme"), Some(Family::Model));
        assert_eq!(family("M09X01"), Some(Family::VPiano));
    }

    /// The wave group id a tone stores decodes to the product, not to a bank slot.
    ///
    /// Read off a FANTOM-6 with `dump-wave-groups`, one selected sound per bank; see
    /// `docs/FORMAT.md`.
    #[test]
    fn a_wave_group_id_names_the_product_that_carries_the_wave() {
        assert_eq!(wave_group_product(1005), Some("EXZ005"));
        assert_eq!(wave_group_product(1006), Some("EXZ006"));
        assert_eq!(wave_group_product(1015), Some("EXZ015"));

        // An internal ROM wave keeps its own small group ids in the same field, and a partial
        // that once played a sample leaves a stale one there. Neither is an expansion.
        assert_eq!(wave_group_product(8), None);
        assert_eq!(wave_group_product(11), None);
        assert_eq!(wave_group_product(1000), None);
        assert_eq!(wave_group_product(10004), None);

        // The arithmetic alone would answer `EXZ200` here. No such expansion has been seen, so
        // the id reads as itself.
        assert_eq!(wave_group_product(1200), None);
    }

    /// Every wave expansion this build catalogs was read back off the instrument, so every one of
    /// them has to survive the decode — the arithmetic is not fitted to the two ids that started it.
    #[test]
    fn every_catalogued_wave_expansion_decodes_from_its_id() {
        let codes: Vec<&str> = products()
            .iter()
            .map(|product| product.code)
            .filter(|code| code.starts_with("EXZ"))
            .collect();
        assert!(codes.len() >= 15, "{codes:?}");
        for code in codes {
            let number: u16 = code[3..].parse().expect("EXZnnn");
            assert_eq!(wave_group_product(EXZ_WAVE_GROUP_BASE + number), Some(code));
        }
    }
}
