//! Roland's parameter map: file bytes on one side, SysEx addresses on the other.
//!
//! The same map describes both. A record on disk is its parameter blocks packed end to end, with
//! multi-nibble wire fields stored as one little-endian integer and signed fields stored
//! zero-centred, so one table serves the librarian reading a file and the transport talking to the
//! instrument. See `docs/FORMAT.md`.
//!
//! - [`tone`] — a 1632-byte ZEN-Core tone record (`PATa`), generated by `tools/gen_params.py`.
//! - [`scene`] — a 3572-byte scene record (`PRFa`), generated by `tools/gen_scene_params.py`.
//!
//! The two are generated from different sources, for the reason recorded in `docs/FORMAT.md`: the
//! upstream editor data covers tones, drum kits and the MODEL engines but has no scene group at
//! all, so the scene table comes from the FANTOM MIDI Implementation instead.

pub mod scene;
pub mod tone;

/// One parameter, in both representations.
pub struct Param {
    pub id: &'static str,
    /// Offset within the file block.
    pub byte_offset: u16,
    /// Width in the file, little-endian.
    pub len_bytes: u8,
    /// Offset within the SysEx block.
    pub sysex_offset: u16,
    /// Width on the wire in 4-bit nibbles; 1 means a plain 7-bit byte.
    pub len_sysex: u8,
    /// Added to the file value to get the wire value (bias for signed fields).
    pub bias: i32,
    /// The wire address exists but carries nothing: send zero, never compare.
    /// A FANTOM-6 stores a phrase reference in two of these and does not report it.
    pub reserved: bool,
}

/// A parameter block, addressed as a unit by RQ1/DT1.
pub struct Block {
    pub name: &'static str,
    pub byte_len: u16,
    pub sysex_len: u16,
    pub params: &'static [Param],
}

impl Block {
    /// The parameter with this id, if the block has one.
    pub fn param(&self, id: &str) -> Option<&'static Param> {
        self.params.iter().find(|p| p.id == id)
    }
}

/// One placement of a block within a record.
pub struct Instance {
    pub block: &'static Block,
    /// Offset of this instance within the file record.
    pub byte_offset: u16,
    /// Address offset from the record's base SysEx address.
    pub sysex_offset: [u8; 3],
}

/// Read a parameter's raw value out of a file record slice, little-endian.
///
/// This is the stored value, still zero-centred for signed fields — [`Param::bias`] is what turns
/// it into the number the panel and the wire use.
pub fn file_value(rec: &[u8], p: &Param) -> u32 {
    let at = p.byte_offset as usize;
    let mut v = 0u32;
    for i in (0..p.len_bytes as usize).rev() {
        v = (v << 8) | rec[at + i] as u32;
    }
    v
}

/// Read a parameter as the panel displays it.
///
/// A field with a [`Param::bias`] is stored zero-centred, which means its file bytes are
/// two's-complement: pan `0xf0` is −16, and goes out on the wire as −16 + 64 = `0x30`. Reading such
/// a field unsigned gives 240 and a nonsense display, so the bias is also the flag that says to
/// sign-extend. An unbiased field is returned as-is.
pub fn display_value(rec: &[u8], p: &Param) -> i32 {
    let v = file_value(rec, p);
    if p.bias == 0 {
        return v as i32;
    }
    match p.len_bytes {
        1 => v as u8 as i8 as i32,
        2 => v as u16 as i16 as i32,
        _ => v as i32,
    }
}

impl Instance {
    fn slice<'a>(&self, record: &'a [u8]) -> Option<&'a [u8]> {
        let at = self.byte_offset as usize;
        record.get(at..at + self.block.byte_len as usize)
    }

    /// Read one named parameter of this block instance out of a whole record.
    ///
    /// `None` when the block has no such parameter or the record is too short, so a caller can ask
    /// for a field this instrument's map does not carry without knowing the block's contents.
    pub fn read(&self, record: &[u8], id: &str) -> Option<u32> {
        let p = self.block.param(id)?;
        Some(file_value(self.slice(record)?, p))
    }

    /// Read one named parameter as the panel displays it; see [`display_value`].
    pub fn read_display(&self, record: &[u8], id: &str) -> Option<i32> {
        let p = self.block.param(id)?;
        Some(display_value(self.slice(record)?, p))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::container::{RawZone, ZoneSettings};

    /// The blocks of a scene record must tile it exactly: no gap, no overlap, nothing past the
    /// end. This is what makes the layout a *map* rather than a set of lucky offsets — a wrong
    /// length anywhere shifts everything after it and this fails.
    #[test]
    fn scene_blocks_tile_the_record_exactly() {
        let mut at = 0usize;
        for inst in scene::SCENE {
            assert_eq!(
                inst.byte_offset as usize, at,
                "{} starts at {:#x}, expected {:#x}",
                inst.block.name, inst.byte_offset, at
            );
            at += inst.block.byte_len as usize;
        }
        assert_eq!(at, scene::RECORD_LEN);
    }

    #[test]
    fn every_parameter_fits_inside_its_block() {
        for block in [&scene::SCENE_COMMON, &scene::SCENE_ZONE, &scene::ZONE_CONTROL] {
            for p in block.params {
                assert!(
                    p.byte_offset as usize + p.len_bytes as usize <= block.byte_len as usize,
                    "{}.{} runs past the block",
                    block.name,
                    p.id
                );
            }
        }
    }

    /// The scene table is generated from Roland's MIDI Implementation; these offsets were found
    /// years earlier by controlled single-variable edits on a FANTOM-6 and are already encoded in
    /// [`crate::container`] and [`crate::codec`]. They must agree.
    #[test]
    fn agrees_with_the_offsets_confirmed_by_controlled_edit() {
        let zone0 = scene::SCENE
            .iter()
            .find(|i| i.block.name == "Scene Zone")
            .expect("scene has a zone table");
        assert_eq!(zone0.byte_offset as usize, ZoneSettings::TABLE_OFFSET);
        assert_eq!(zone0.block.byte_len as usize, ZoneSettings::LEN);
        assert_eq!(zone0.block.param("Zone_Level").unwrap().byte_offset, 0x07);
        assert_eq!(
            zone0.block.param("Tone_Bank_Select_MSB").unwrap().byte_offset,
            0x00
        );

        // The zone table `container::zone` reads at 0x6d0 is Zone Control, which really begins at
        // 0x6d4 — its leading four bytes are the tail of the last Zone EQ entry.
        let ctrl = scene::SCENE
            .iter()
            .find(|i| i.block.name == "Zone Control")
            .expect("scene has a zone control table");
        assert_eq!(ctrl.byte_offset as usize, RawZone::TABLE_OFFSET + 4);
        assert_eq!(ctrl.block.byte_len as usize, RawZone::LEN);
        let lower = ctrl.block.param("Keyboard_Control_Range_Lower").unwrap();
        let upper = ctrl.block.param("Keyboard_Control_Range_Upper").unwrap();
        assert_eq!(lower.byte_offset as usize + 4, 0x08);
        assert_eq!(upper.byte_offset as usize + 4, 0x09);
    }

    /// The scene memo sits at file `+0x40` but wire `+0x42`, because Scene Tempo before it is four
    /// nibbles on the wire and two bytes in the file. Deriving that skew correctly is the whole
    /// packing rule in one field, and `codec` hard-codes the answer.
    #[test]
    fn scene_memo_lands_where_the_codec_reads_it() {
        let memo = scene::SCENE_COMMON.param("Scene_Memo_1").unwrap();
        assert_eq!(memo.byte_offset, 0x40);
        assert_eq!(memo.sysex_offset, 0x42);
        let tempo = scene::SCENE_COMMON.param("Scene_Tempo").unwrap();
        assert_eq!((tempo.byte_offset, tempo.len_bytes, tempo.len_sysex), (0x38, 2, 4));
    }

    /// The two tables come from different sources — the tone table from Roland's editor data, the
    /// scene table from the MIDI Implementation PDF — and both contain the MFX block. They agree
    /// on its file length, including the four bytes of padding neither document states.
    #[test]
    fn both_sources_agree_on_the_mfx_block() {
        assert_eq!(scene::IFX.byte_len, tone::MFX.byte_len);
        assert_eq!(scene::IFX.sysex_len, tone::MFX.sysex_len);
    }
}
