//! Roland's parameter map: file bytes on one side, SysEx addresses on the other.
//!
//! The same map describes both. A record on disk is its parameter blocks packed end to end, with
//! multi-nibble wire fields stored as one little-endian integer and signed fields stored
//! zero-centred, so one table serves the librarian reading a file and the transport talking to the
//! instrument. See `docs/FORMAT.md`.
//!
//! - [`tone`] — a 1632-byte ZEN-Core tone record (`PATa`), generated by `tools/gen_params.py`.
//!
//! This lives in `fantom-core` rather than beside the SysEx transport because it is as much a fact
//! about the file as about the wire: the librarian reads it with no MIDI port in sight, and
//! `fantom-cli` depends on this crate alone.

pub mod tone;

/// One parameter, in both representations.
pub struct Param {
    pub id: &'static str,
    /// Offset within the file block.
    pub byte_offset: u16,
    /// Width in the file, little-endian.
    pub len_bytes: u8,
    /// Offset within the SysEx block.
    pub sysex_offset: u16,
    /// Width on the wire in 4-bit nibbles; 1 means a plain 7-bit byte.
    pub len_sysex: u8,
    /// Added to the file value to get the wire value (bias for signed fields).
    pub bias: i32,
    /// The wire address exists but carries nothing: send zero, never compare.
    /// A FANTOM-6 stores a phrase reference in two of these and does not report it.
    pub reserved: bool,
}

/// A parameter block, addressed as a unit by RQ1/DT1.
pub struct Block {
    pub name: &'static str,
    pub byte_len: u16,
    pub sysex_len: u16,
    pub params: &'static [Param],
}

impl Block {
    /// The parameter with this id, if the block has one.
    pub fn param(&self, id: &str) -> Option<&'static Param> {
        self.params.iter().find(|p| p.id == id)
    }
}

/// One placement of a block within a record.
pub struct Instance {
    pub block: &'static Block,
    /// Offset of this instance within the file record.
    pub byte_offset: u16,
    /// Address offset from the record's base SysEx address.
    pub sysex_offset: [u8; 3],
}

impl Instance {
    fn slice<'a>(&self, record: &'a [u8]) -> Option<&'a [u8]> {
        let at = self.byte_offset as usize;
        record.get(at..at + self.block.byte_len as usize)
    }

    /// Read one named parameter of this block instance out of a whole record.
    ///
    /// `None` when the block has no such parameter or the record is too short, so a caller can ask
    /// for a field this instrument's map does not carry without knowing the block's contents.
    pub fn read(&self, record: &[u8], id: &str) -> Option<u32> {
        let p = self.block.param(id)?;
        Some(file_value(self.slice(record)?, p))
    }
}

/// Read a parameter's raw value out of a file record slice, little-endian.
///
/// This is the stored value, still zero-centred for signed fields — [`Param::bias`] is what turns
/// it into the number the panel and the wire use.
pub fn file_value(rec: &[u8], p: &Param) -> u32 {
    let at = p.byte_offset as usize;
    let mut v = 0u32;
    for i in (0..p.len_bytes as usize).rev() {
        v = (v << 8) | rec[at + i] as u32;
    }
    v
}
