#!/usr/bin/env python3
"""Generate the ZEN-Core parameter table from DrKnackerator's Roland-Structured-Storage.

    curl -sO https://raw.githubusercontent.com/DrKnackeratorStrikesAgain/\
Roland-Structured-Storage/HEAD/jupiter.js
    python3 tools/gen_params.py jupiter.js > crates/fantom-core/src/params/tone.rs

The source is MIT-licensed and derives its layouts from Roland's own editor data for
other ZEN-Core instruments. Fields are checked against hardware by `validate-params`.
"""

import json
import re
import sys

# Blocks reachable from a ZEN-Core tone (PCMEX). Others in the source cover drum kits
# and the MODEL engines; add them here when their file areas get decoded.
GROUP = "PCMEX"

# The source models a superset of ZEN-Core; where the FANTOM MIDI Implementation gives a
# smaller block, it wins and the fields past the end are dropped. Confirmed by RQ1: the
# instrument returns 29 bytes for [Tone Synth Partial], and 0x1B onward is Reserved.
FANTOM_SYSEX_LEN = {"PCMS_PTL": 29}


def load(path):
    src = open(path).read()
    src = src[src.index("{"):]
    src = re.sub(r",(\s*[}\]])", r"\1", src)  # JS trailing commas
    return json.loads(src)


def main():
    doc = load(sys.argv[1])
    blocks, group = doc["blocks"], doc["groups"][GROUP]
    used = sorted({e["blockName"] for e in group["blocks"]})

    out = [
        "//! ZEN-Core tone parameter table: file bytes <-> SysEx addresses.",
        "//!",
        "//! Generated by `tools/gen_params.py`; do not edit by hand. Source data from",
        "//! <https://github.com/DrKnackeratorStrikesAgain/Roland-Structured-Storage> (MIT).",
        "",
        "use super::{Block, Display, Instance, Param};",
        "",
    ]

    for name in used:
        b = blocks[name]
        sysex_len = FANTOM_SYSEX_LEN.get(name, b["sysexLength"])
        out.append(f"static {name}_PARAMS: &[Param] = &[")
        for p in b["parameters"]:
            if p.get("isPadding") or p.get("sysexOffset") is None:
                continue  # padding, and file-only fields the wire does not carry
            if p["sysexOffset"] + p["lengthSysex"] > sysex_len:
                continue  # past the end of the block on this instrument
            reserved = str(
                p["description"] == "Reserved" and p.get("dataRange") == [0, 0]
            ).lower()
            out.append(
                f'    Param {{ id: "{p["id"]}", byte_offset: {p["byteOffset"]}, '
                f'len_bytes: {p["lengthBytes"]}, sysex_offset: {p["sysexOffset"]}, '
                f'len_sysex: {p["lengthSysex"]}, bias: {p.get("sysexValueOffset", 0)}, '
                f'reserved: {reserved}, display: Display::Number, unit: "" }},'
            )
        out += ["];", ""]
        out += [
            f"pub static {name}: Block = Block {{",
            f'    name: "{name}",',
            f'    byte_len: {b["byteLength"]},',
            f"    sysex_len: {sysex_len},",
            f"    params: {name}_PARAMS,",
            "};",
            "",
        ]

    total = sum(e["totalByteLength"] for e in group["blocks"])
    out.append(f"/// A ZEN-Core tone record ({total} bytes), block by block.")
    out.append("pub static TONE: &[Instance] = &[")
    for e in group["blocks"]:
        for i, (bo, sx) in enumerate(zip(e["byteOffset"], e["sysexOffset"])):
            hi, mid, lo = (int(x, 16) for x in sx.split())
            out.append(
                f"    Instance {{ block: &{e['blockName']}, byte_offset: {bo}, "
                f"sysex_offset: [0x{hi:02x}, 0x{mid:02x}, 0x{lo:02x}] }},"
            )
            _ = i
    out += ["];", ""]
    print("\n".join(out))


if __name__ == "__main__":
    main()
